# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ImageService.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'ImageService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12ImageService.proto\"\x19\n\x04Info\x12\x11\n\tfile_name\x18\x01 \x01(\t\"*\n\x0eUploadResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\r\"?\n\rUploadRequest\x12\x15\n\x04info\x18\x01 \x01(\x0b\x32\x05.InfoH\x00\x12\x0f\n\x05\x63hunk\x18\x02 \x01(\x0cH\x00\x42\x06\n\x04\x64\x61ta2;\n\x0cImageService\x12+\n\x06Upload\x12\x0e.UploadRequest\x1a\x0f.UploadResponse(\x01\x42\x07Z\x05./apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ImageService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\005./api'
  _globals['_INFO']._serialized_start=22
  _globals['_INFO']._serialized_end=47
  _globals['_UPLOADRESPONSE']._serialized_start=49
  _globals['_UPLOADRESPONSE']._serialized_end=91
  _globals['_UPLOADREQUEST']._serialized_start=93
  _globals['_UPLOADREQUEST']._serialized_end=156
  _globals['_IMAGESERVICE']._serialized_start=158
  _globals['_IMAGESERVICE']._serialized_end=217
# @@protoc_insertion_point(module_scope)
