// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: api/ModelService.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextEmbeddingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Embedding []float64 `protobuf:"fixed64,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
}

func (x *TextEmbeddingResponse) Reset() {
	*x = TextEmbeddingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ModelService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextEmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextEmbeddingResponse) ProtoMessage() {}

func (x *TextEmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ModelService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextEmbeddingResponse.ProtoReflect.Descriptor instead.
func (*TextEmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_api_ModelService_proto_rawDescGZIP(), []int{0}
}

func (x *TextEmbeddingResponse) GetEmbedding() []float64 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type ImageEmbeddingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Embedding []float64 `protobuf:"fixed64,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
}

func (x *ImageEmbeddingResponse) Reset() {
	*x = ImageEmbeddingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ModelService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageEmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageEmbeddingResponse) ProtoMessage() {}

func (x *ImageEmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ModelService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageEmbeddingResponse.ProtoReflect.Descriptor instead.
func (*ImageEmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_api_ModelService_proto_rawDescGZIP(), []int{1}
}

func (x *ImageEmbeddingResponse) GetEmbedding() []float64 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type TextEmbeddingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *TextEmbeddingRequest) Reset() {
	*x = TextEmbeddingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ModelService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextEmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextEmbeddingRequest) ProtoMessage() {}

func (x *TextEmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ModelService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextEmbeddingRequest.ProtoReflect.Descriptor instead.
func (*TextEmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_api_ModelService_proto_rawDescGZIP(), []int{2}
}

func (x *TextEmbeddingRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ImageEmbeddingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chunk []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
}

func (x *ImageEmbeddingRequest) Reset() {
	*x = ImageEmbeddingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ModelService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageEmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageEmbeddingRequest) ProtoMessage() {}

func (x *ImageEmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ModelService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageEmbeddingRequest.ProtoReflect.Descriptor instead.
func (*ImageEmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_api_ModelService_proto_rawDescGZIP(), []int{3}
}

func (x *ImageEmbeddingRequest) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

var File_api_ModelService_proto protoreflect.FileDescriptor

var file_api_ModelService_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x70, 0x69, 0x2f, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35, 0x0a, 0x15, 0x54, 0x65, 0x78, 0x74,
	0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x01, 0x52, 0x09, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x22,
	0x36, 0x0a, 0x16, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6d, 0x62,
	0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x09, 0x65, 0x6d,
	0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x22, 0x2a, 0x0a, 0x14, 0x54, 0x65, 0x78, 0x74, 0x45,
	0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x22, 0x2d, 0x0a, 0x15, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x45, 0x6d, 0x62, 0x65,
	0x64, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x63, 0x68, 0x75,
	0x6e, 0x6b, 0x32, 0x93, 0x01, 0x0a, 0x0c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x54, 0x65, 0x78, 0x74, 0x45, 0x6d, 0x62, 0x65, 0x64,
	0x64, 0x69, 0x6e, 0x67, 0x12, 0x15, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x45, 0x6d, 0x62, 0x65, 0x64,
	0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x54, 0x65,
	0x78, 0x74, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x45, 0x6d, 0x62, 0x65,
	0x64, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x45, 0x6d, 0x62,
	0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x61, 0x70,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_ModelService_proto_rawDescOnce sync.Once
	file_api_ModelService_proto_rawDescData = file_api_ModelService_proto_rawDesc
)

func file_api_ModelService_proto_rawDescGZIP() []byte {
	file_api_ModelService_proto_rawDescOnce.Do(func() {
		file_api_ModelService_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_ModelService_proto_rawDescData)
	})
	return file_api_ModelService_proto_rawDescData
}

var file_api_ModelService_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_ModelService_proto_goTypes = []any{
	(*TextEmbeddingResponse)(nil),  // 0: TextEmbeddingResponse
	(*ImageEmbeddingResponse)(nil), // 1: ImageEmbeddingResponse
	(*TextEmbeddingRequest)(nil),   // 2: TextEmbeddingRequest
	(*ImageEmbeddingRequest)(nil),  // 3: ImageEmbeddingRequest
}
var file_api_ModelService_proto_depIdxs = []int32{
	2, // 0: ModelService.TextEmbedding:input_type -> TextEmbeddingRequest
	3, // 1: ModelService.ImageEmbedding:input_type -> ImageEmbeddingRequest
	0, // 2: ModelService.TextEmbedding:output_type -> TextEmbeddingResponse
	1, // 3: ModelService.ImageEmbedding:output_type -> ImageEmbeddingResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_ModelService_proto_init() }
func file_api_ModelService_proto_init() {
	if File_api_ModelService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_ModelService_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TextEmbeddingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ModelService_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ImageEmbeddingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ModelService_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*TextEmbeddingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ModelService_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ImageEmbeddingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_ModelService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ModelService_proto_goTypes,
		DependencyIndexes: file_api_ModelService_proto_depIdxs,
		MessageInfos:      file_api_ModelService_proto_msgTypes,
	}.Build()
	File_api_ModelService_proto = out.File
	file_api_ModelService_proto_rawDesc = nil
	file_api_ModelService_proto_goTypes = nil
	file_api_ModelService_proto_depIdxs = nil
}
