FROM golang:alpine AS build

RUN apk --update add ca-certificates git

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /image-retrieval-gateway

CMD ["/image-retrieval-gateway"]