# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto.ModelService_pb2 as ModelService__pb2


class ModelServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TextEmbedding = channel.unary_unary(
            '/ModelService/TextEmbedding',
            request_serializer=ModelService__pb2.TextEmbeddingRequest.SerializeToString,
            response_deserializer=ModelService__pb2.TextEmbeddingResponse.FromString,
        )
        self.ImageEmbedding = channel.stream_unary(
            '/ModelService/ImageEmbedding',
            request_serializer=ModelService__pb2.ImageEmbeddingRequest.SerializeToString,
            response_deserializer=ModelService__pb2.ImageEmbeddingResponse.FromString,
        )


class ModelServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TextEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImageEmbedding(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'TextEmbedding': grpc.unary_unary_rpc_method_handler(
            servicer.TextEmbedding,
            request_deserializer=ModelService__pb2.TextEmbeddingRequest.FromString,
            response_serializer=ModelService__pb2.TextEmbeddingResponse.SerializeToString,
        ),
        'ImageEmbedding': grpc.stream_unary_rpc_method_handler(
            servicer.ImageEmbedding,
            request_deserializer=ModelService__pb2.ImageEmbeddingRequest.FromString,
            response_serializer=ModelService__pb2.ImageEmbeddingResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'ModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))

 # This class is part of an EXPERIMENTAL API.


class ModelService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TextEmbedding(request,
                      target,
                      options=(),
                      channel_credentials=None,
                      call_credentials=None,
                      insecure=False,
                      compression=None,
                      wait_for_ready=None,
                      timeout=None,
                      metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ModelService/TextEmbedding',
                                             ModelService__pb2.TextEmbeddingRequest.SerializeToString,
                                             ModelService__pb2.TextEmbeddingResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ImageEmbedding(request_iterator,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/ModelService/ImageEmbedding',
                                              ModelService__pb2.ImageEmbeddingRequest.SerializeToString,
                                              ModelService__pb2.ImageEmbeddingResponse.FromString,
                                              options, channel_credentials,
                                              insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
